apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shm-sampleapp-certificate
spec:
  dnsNames:
  - 'shm.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: shm-sampleapp-cert